server.port: 8081
spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${RDB_HOST:127.0.0.1}:${RDB_PORT:3310}/review
        username: ${RDB_USERNAME:root}
        password: ${RDB_PASSWORD:0000}
        hikari:
            initialization-fail-timeout: -1
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: false
                format_sql: false
        database-platform: org.hibernate.dialect.MySQLDialect
    redis:
        host: ${REDIS_HOST:127.0.0.1}
        port: ${REDIS_PORT:6390}
    rabbitmq:
        host: ${RABBIT_HOST:127.0.0.1}
        port: ${RABBIT_PORT:5680}
servlet:
    multipart:
        max-file-size: 2MB
        max-request-size: 10MB
jwt:
    secret:
        key: 01234567890123456789012345678901234567890123456789
