spring:
  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review
    username: root
    password: '0000'
  # Redis
  redis:
    host: localhost
    port: 6379
  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# Logging
logging:
  level:
    org.hibernate.SQL: debug