# Server
server:
  port: 8081

# Spring
spring:
  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review
    username: root
    password: '0000'
  # Redis
  redis:
    host: redis_host
    port: 6379
  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  # File
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

# Upload File Path (WAR)
file:
  upload:
    root: s112123/tomcat/webapps/ROOT/WEB-INF/classes/static/uploads/
    directories:
      profiles: profiles/
      reviews: reviews/
      temps: temps/

# Logging
logging:
  level:
    org.hibernate.SQL: debug

# JWT
jwt:
  secret:
    key: 01234567890123456789012345678901234567890123456789

# Email
email:
  naver:
    host: smtp.naver.com
    username: Naver Email ID
    password: Naver Email Password
    port: 465