# Upload File Path
file:
    upload:
        root: /uploads
        directories:
            profiles: profiles
            reviews: reviews
            temps: temps
# Email
email:
    naver:
        host: smtp.naver.com
        username: Naver Email ID
        password: Naver Email Password
        port: 465