# Server
server:
  port: 8081

# Spring
spring:
  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review
    username: root
    password: '0000'
  # Redis
  redis:
    host: localhost
    port: 6379
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# File
servlet:
  multipart:
    max-file-size: 3MB
    max-request-size: 10MB

# Upload File Path
file:
  upload:
    root: D:\\uploads
    directories:
      profiles: profiles
      reviews: reviews
      temps: temps

# JWT
jwt:
  secret:
    key: 01234567890123456789012345678901234567890123456789