server.port: 8081
spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${RDB_HOST:127.0.0.1}:${RDB_PORT:3306}/review
        username: ${RDB_USERNAME:root}
        password: ${RDB_PASSWORD:0000}
        hikari:
            initialization-fail-timeout: -1
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    redis:
        host: ${REDIS_HOST:127.0.0.1}
        port: ${REDIS_PORT:6380}
    rabbitmq:
        host: ${RABBIT_HOST:127.0.0.1}
        port: ${RABBIT_PORT:5672}
servlet:
    multipart:
        max-file-size: 1MB
        max-request-size: 10MB
jwt:
    secret:
        key: 01234567890123456789012345678901234567890123456789
